services:
  - type: web
    name: resumegenie-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "cd backend && uvicorn api:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: 10000